name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install --force
      - run: npm run build

      - name: Zip dist
        run: |
          cd dist
          zip -r ../dist.zip .
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: latest
          files: dist.zip

      - name: Trigger deploy
        run: |
          curl https://tnservice.vn/webhook.php